# Generated by Django 2.2.6 on 2019-10-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(default='0', max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='media/author')),
            ],
        ),
    ]
