# Generated by Django 3.0.7 on 2020-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(default='0', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('average_rating', models.FloatField(default=0)),
                ('about', models.TextField(null=True)),
                ('image', models.URLField(default='https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png')),
            ],
        ),
    ]
