# Generated by Django 2.2.6 on 2019-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20191015_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
