# Generated by Django 2.2.6 on 2019-10-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='about',
        ),
    ]
