# Generated by Django 2.2.6 on 2020-06-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.URLField(default='https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png'),
        ),
    ]
