# Generated by Django 3.0.7 on 2020-06-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(default='0', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'ISBN'), ('G', 'GID')], default='I', max_length=1)),
                ('book_id', models.CharField(default='0', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('average_rating', models.FloatField(default=0)),
                ('description', models.TextField(default='', null=True)),
                ('image', models.URLField()),
                ('genre', models.ManyToManyField(blank=True, to='book.Genre')),
                ('similar_books', models.ManyToManyField(blank=True, to='book.Book')),
            ],
        ),
    ]
