# Generated by Django 2.2.6 on 2019-10-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(default='0', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='0', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(default='', null=True)),
                ('image', models.ImageField(default='', upload_to='media/book')),
                ('author', models.ManyToManyField(to='author.Author')),
                ('genre', models.ManyToManyField(blank=True, to='book.Genre')),
            ],
        ),
    ]
