# Generated by Django 2.2.6 on 2019-10-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191015_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='similar_books',
            field=models.ManyToManyField(blank=True, to='book.Book'),
        ),
    ]
