# Generated by Django 2.2.6 on 2019-10-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_similar_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('I', 'ISBN'), ('G', 'GID')], default='I', max_length=1),
        ),
    ]
