# Generated by Django 3.0.7 on 2020-06-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_auto_20200606_0602'),
        ('book', '0007_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='author.Author'),
        ),
    ]
