# Generated by Django 2.2.6 on 2019-10-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=20, unique=True)),
                ('action_text', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('body', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
