# Generated by Django 3.0.7 on 2020-06-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200606_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='action_text',
            field=models.CharField(max_length=500),
        ),
    ]
