# Generated by Django 2.2.6 on 2019-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default='https://images.gr-assets.com/users/1571064163p2/97134500.jpg'),
            preserve_default=False,
        ),
    ]
