# Generated by Django 3.0.7 on 2020-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200606_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.CharField(max_length=100),
        ),
    ]
