# Generated by Django 2.2.6 on 2019-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.CharField(max_length=20),
        ),
    ]
