# Generated by Django 3.0.7 on 2020-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200606_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(max_length=720, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='request_token',
            field=models.CharField(default='', max_length=720),
        ),
        migrations.AddField(
            model_name='customuser',
            name='request_token_secret',
            field=models.CharField(default='', max_length=720),
        ),
    ]
