# Generated by Django 2.2.6 on 2019-10-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191017_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
    ]
