# Generated by Django 3.0.7 on 2020-06-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200606_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token_secret',
            field=models.CharField(max_length=720, null=True),
        ),
    ]
