# Generated by Django 2.2.6 on 2019-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191017_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='action_text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
