# Generated by Django 3.0.7 on 2020-06-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_access_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.CharField(max_length=200),
        ),
    ]
