# Generated by Django 2.2.6 on 2019-10-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191018_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
