# Generated by Django 2.2.6 on 2019-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fav_books',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
