# Generated by Django 2.2.6 on 2019-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191018_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='best_quote',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
