# Generated by Django 2.2.6 on 2019-10-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_type'),
        ('user', '0012_customuser_best_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('books', models.ManyToManyField(blank=True, to='book.Book')),
            ],
        ),
    ]
