# Generated by Django 2.2.6 on 2019-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
