# Generated by Django 2.2.6 on 2019-10-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20191019_2227'),
        ('user', '0014_auto_20191019_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 'did not like it'), (2, 'it was ok'), (3, 'liked it'), (4, 'really liked it'), (5, 'it was amazing')], default=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Shelf')),
            ],
        ),
    ]
