# Generated by Django 2.2.6 on 2019-10-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
