# Generated by Django 2.2.6 on 2019-11-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_shelf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 'no rating'), (1, 'did not like it'), (2, 'it was ok'), (3, 'liked it'), (4, 'really liked it'), (5, 'it was amazing')], default=3),
        ),
    ]
